### PR TITLE
🐛 Fix empty data/labels handling

### LINKED ISSUE #375: Axis tick labels are rendered outside of the chart container in some cases
### Problem description

I'm using Stacked Bar Chart vue2 component (from `@adyen/lume@1.6.5`) with no data (empty values array) in situations when there is no data available yet (it should be possible accordingly to documentation, at least it doesn't state otherwise). In such situation I'd like to render empty chart with 7 columns for each of the past 7 days on the x axis, and 10 ticks for values from 0 to 10 on the y axis.

However when I try to render chart for such use case, tick labels on the x axis are rendered partially outside of the chart container. Here is component that can be used to reproduce the issue:

```html
<template>
  <lume-stacked-bar-chart
    :labels="['1', '2', '3', '4', '5', '6', '7']"
    :data="[{ values: [] }]"
    :y-scale="yScale"
  />
</template>

<script>
import { scaleLinear } from 'd3';
import { LumeStackedBarChart } from '@adyen/lume';

export default {
  components: { LumeStackedBarChart },
  setup() {
    const yScale = (data, labels, size) => scaleLinear().domain([0, 10]).range([0, size.height]);
    return { yScale };
  },
};
</script>
```

### Reproduction URL

_No response_

### Reproduction steps

1. Create new component based on the example from the "Problem description" section
2. Render it in the browser. Chart would be rendered like on the example below, with x axis tick labels partially visible (only 4 -7 values are visible)
Screenshot 2024-01-02 at 15 27 56

### Expected behavior

Tick labels on both axis are correctly aligned to the chart container, so all 1-7 values are visible on the x axis.

### Screenshots

_No response_

### Logs

_No response_

### Browsers

Chrome

### OS

_No response_

### Validations

- [X] Follow our [Code of Conduct](https://github.com/Adyen/lume/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/Adyen/lume/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/Adyen/lume/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Lume issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### PR DESCRIPTION
**Pull request by joao-m-santos**
Fixes #375

## 📝 Description

> - When one of the dimensions (data, labels) is empty, no longer generates a scale

## 💥 Is this a breaking change (Yes/No):

- [x] No
- [ ] Yes (please describe the impact and migration path for existing Lume users)

## 📝 Additional Information

>

### Before submitting the PR, please make sure you do the following

- [x] Read the [Contributing Guidelines](https://github.com/Adyen/lume/blob/main/CONTRIBUTING.md).
- [x] Check that there isn't already a PR that solves the problem the same way to avoid creating a duplicate.
- [x] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `fixes #123`).
- [x] Ideally, include relevant tests that fail without this PR but pass with it.

### CODE REVIEW

File: packages/lib/src/components/core/lume-axis/lume-axis.vue [hunk 1]
```diff
@@ -181,13 +181,17 @@ const { allOptions } = useOptions<AxisOptions>(
 const { showTick } = useSkip(scale, tickRefs, allOptions);
 
 const axisTransform = computed(() => {
+  if (computedType.value === 'y') {
+    console.log(isEmpty.value, scale.value);
+  }
```
Comment (govind-srinidhi) [inline packages/lib/src/components/core/lume-axis/lume-axis.vue:186]: log message 😉

Comment (joao-m-santos) [reply packages/lib/src/components/core/lume-axis/lume-axis.vue:186]: oops 😬

**Review by govind-srinidhi — APPROVED** [review]
