### PR TITLE
🐛 Make skip option reactive

### LINKED ISSUE #369: `skip` axis option is not reactive
### Problem description

The `skip` option for the `lume-axis` is not reactive.

### Reproduction URL

_No response_

### Reproduction steps

1. Add any Lume chart with axes
2. In a setTimeout, change the options value to add a `skip` value to a band scale axis
3. The new `skip` value is not used and the axis remains the same

### Expected behavior

1. Add any Lume chart with axes
2. In a setTimeout, change the options value to add a `skip` value to a band scale axis
3. The new `skip` value is used and the axis re-renders based on the new value

### Screenshots

_No response_

### Logs

_No response_

### Browsers

_No response_

### OS

_No response_

### Validations

- [X] Follow our [Code of Conduct](https://github.com/Adyen/lume/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/Adyen/lume/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/Adyen/lume/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Lume issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### PR DESCRIPTION
**Pull request by joao-m-santos**
Fixes #369 

## 📝 Description

> - Passed the option ref instead of the static value to the useSkip composable

## 💥 Is this a breaking change (Yes/No):

- [x] No
- [ ] Yes (please describe the impact and migration path for existing Lume users)

## 📝 Additional Information

>

### Before submitting the PR, please make sure you do the following

- [x] Read the [Contributing Guidelines](https://github.com/Adyen/lume/blob/main/CONTRIBUTING.md).
- [x] Check that there isn't already a PR that solves the problem the same way to avoid creating a duplicate.
- [x] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `fixes #123`).
- [x] Ideally, include relevant tests that fail without this PR but pass with it.

### CODE REVIEW

File: packages/lib/src/components/core/lume-axis/composables/lume-skip.ts [hunk 1]
```diff
@@ -9,12 +10,12 @@ const SAFETY_MARGIN = 0.2; // 20% of the average width
...
  * @param scale A d3 scale.
  * @param tickRefs Template reference to the tick text elements
- * @param skipNumber Optional amount of ticks to skip
+ * @param options The axis options.
  */
 export function useSkip(
   scale: Ref<Scale>,
   tickRefs: Ref<Array<{ ref: SVGTextElement }>>,
-  skipNumber?: true | number
+  options: Ref<AxisOptions>
```
Comment (govind-srinidhi) [inline packages/lib/src/components/core/lume-axis/composables/lume-skip.ts:18]: that was a great catch!
non-reactive as we were not passing the composable with a reactive value 🤯
