### PR TITLE
🐛 Update gridlines on container size change

### LINKED ISSUE #377: After the first render Stacked Bar Chart doesn't correctly react to the container resize
### Problem description

When the chart is rendered for the first time, it is correctly placing all its visual elements in the container of the given size. However, once this container is resized, not all chart elements are correctly reacting to the change. See screenshots for more details.

Used v1.6.5

First render:
Screenshot 2024-01-03 at 13 07 38

When downsized:
Screenshot 2024-01-03 at 13 07 50

When expanded:
Screenshot 2024-01-03 at 13 07 59

### Reproduction URL

_No response_

### Reproduction steps

1. Render Stacked Bar Chart and style it to take 100% of the page.
2. Try to resize browser window.

### Expected behavior

All chart visual elements are correctly reacting to the resize.

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Logs

_No response_

### Browsers

Chrome

### OS

_No response_

### Validations

- [X] Follow our [Code of Conduct](https://github.com/Adyen/lume/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/Adyen/lume/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/Adyen/lume/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Lume issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### PR DESCRIPTION
**Pull request by joao-m-santos**
Fixes #377

## 📝 Description

Added a watcher on `containerSize` - if it changes, recalculate the gridlines.

## 💥 Is this a breaking change (Yes/No):

- [x] No
- [ ] Yes (please describe the impact and migration path for existing Lume users)

## 📝 Additional Information

This is needed for cases where the container width changes, so the Y gridlines need to update, but the Y scale doesn't change since the height is the same

### Before submitting the PR, please make sure you do the following

- [x] Read the [Contributing Guidelines](https://github.com/Adyen/lume/blob/main/CONTRIBUTING.md).
- [x] Check that there isn't already a PR that solves the problem the same way to avoid creating a duplicate.
- [x] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `fixes #123`).
- [x] Ideally, include relevant tests that fail without this PR but pass with it.

### CODE REVIEW

**Review by govind-srinidhi — APPROVED** [review]

File: packages/lib/src/components/core/lume-axis/lume-axis.vue [hunk 1]
```diff
@@ -274,18 +274,25 @@ function getTextNode(index: number) {
...
+    })
   );
 }
 
+function updateGridlines() {
+  if (ticksWithAttributes.value) {
+    ticksWithAttributes.value.map((tick) => {
+      tick.gridline = mixins.getGridLinesAttributes();
+      return tick;
+    });
```
Comment (govind-srinidhi) [inline packages/lib/src/components/core/lume-axis/lume-axis.vue:292]: Shouldn't this be assigned to `ticksWithAttributes.value`?
```
ticksWithAttributes.value = ticksWithAttributes.value.map((tick) => {
     tick.gridline = mixins.getGridLinesAttributes();
     return tick;
});
```

**Review by govind-srinidhi — APPROVED** [review]
